// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvayYp-sxFOU5XhagsbxaW4LxJ-LA2w8g',
    appId: '1:509166403453:web:6eee546006cf9511681614',
    messagingSenderId: '509166403453',
    projectId: 'notes-application-flutter',
    authDomain: 'notes-application-flutter.firebaseapp.com',
    storageBucket: 'notes-application-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-4iayWFuKxfgVf-UWkiREkl0F2AqV1w',
    appId: '1:509166403453:android:47b25f84bbb735f6681614',
    messagingSenderId: '509166403453',
    projectId: 'notes-application-flutter',
    storageBucket: 'notes-application-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYsuLgwMIWTRYyCbYVNrbRC5BKrmlsaQ',
    appId: '1:509166403453:ios:9353156db92b0ae9681614',
    messagingSenderId: '509166403453',
    projectId: 'notes-application-flutter',
    storageBucket: 'notes-application-flutter.appspot.com',
    iosClientId: '509166403453-dsqo4f0nvcipph77n66h1n6mqdj1oqti.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYsuLgwMIWTRYyCbYVNrbRC5BKrmlsaQ',
    appId: '1:509166403453:ios:9353156db92b0ae9681614',
    messagingSenderId: '509166403453',
    projectId: 'notes-application-flutter',
    storageBucket: 'notes-application-flutter.appspot.com',
    iosClientId: '509166403453-dsqo4f0nvcipph77n66h1n6mqdj1oqti.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
